package com.entidad;
// Generated 27/01/2015 10:35:24 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Archivo generated by hbm2java
 */
public class Archivo  implements java.io.Serializable {


     private int idArchivo;
     private String nombre;
     private String url;
     private Set denuncias = new HashSet(0);

    public Archivo() {
    }

	
    public Archivo(int idArchivo, String nombre) {
        this.idArchivo = idArchivo;
        this.nombre = nombre;
    }
    public Archivo(int idArchivo, String nombre, String url, Set denuncias) {
       this.idArchivo = idArchivo;
       this.nombre = nombre;
       this.url = url;
       this.denuncias = denuncias;
    }
   
    public int getIdArchivo() {
        return this.idArchivo;
    }
    
    public void setIdArchivo(int idArchivo) {
        this.idArchivo = idArchivo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getDenuncias() {
        return this.denuncias;
    }
    
    public void setDenuncias(Set denuncias) {
        this.denuncias = denuncias;
    }




}


