package com.entidad;
// Generated 27/01/2015 10:35:24 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private int idDireccion;
     private String calle;
     private String colonia;
     private String codigoPostal;
     private String ciudad;
     private String estado;
     private String numeroExterior;
     private String numeroInterior;
     private Set plantels = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Direccion() {
    }

	
    public Direccion(int idDireccion, String calle, String colonia, String codigoPostal, String estado) {
        this.idDireccion = idDireccion;
        this.calle = calle;
        this.colonia = colonia;
        this.codigoPostal = codigoPostal;
        this.estado = estado;
    }
    public Direccion(int idDireccion, String calle, String colonia, String codigoPostal, String ciudad, String estado, String numeroExterior, String numeroInterior, Set plantels, Set usuarios) {
       this.idDireccion = idDireccion;
       this.calle = calle;
       this.colonia = colonia;
       this.codigoPostal = codigoPostal;
       this.ciudad = ciudad;
       this.estado = estado;
       this.numeroExterior = numeroExterior;
       this.numeroInterior = numeroInterior;
       this.plantels = plantels;
       this.usuarios = usuarios;
    }
   
    public int getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(int idDireccion) {
        this.idDireccion = idDireccion;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getNumeroExterior() {
        return this.numeroExterior;
    }
    
    public void setNumeroExterior(String numeroExterior) {
        this.numeroExterior = numeroExterior;
    }
    public String getNumeroInterior() {
        return this.numeroInterior;
    }
    
    public void setNumeroInterior(String numeroInterior) {
        this.numeroInterior = numeroInterior;
    }
    public Set getPlantels() {
        return this.plantels;
    }
    
    public void setPlantels(Set plantels) {
        this.plantels = plantels;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


