package com.entidad;
// Generated 27/01/2015 10:35:24 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Protocolo generated by hbm2java
 */
public class Protocolo  implements java.io.Serializable {


     private ProtocoloId id;
     private String version;
     private Estado estado;
     private String nombre;
     private String descripcion;
     private String objetivo;
     private String leyes;
     private Set procedimientos = new HashSet(0);

    public Protocolo() {
    }

	
    public Protocolo(ProtocoloId id, Estado estado, String nombre, String descripcion) {
        this.id = id;
        this.estado = estado;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Protocolo(ProtocoloId id, Estado estado, String nombre, String descripcion, String objetivo, String leyes, Set procedimientos) {
       this.id = id;
       this.estado = estado;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.objetivo = objetivo;
       this.leyes = leyes;
       this.procedimientos = procedimientos;
    }
   
    public ProtocoloId getId() {
        return this.id;
    }
    
    public void setId(ProtocoloId id) {
        this.id = id;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getObjetivo() {
        return this.objetivo;
    }
    
    public void setObjetivo(String objetivo) {
        this.objetivo = objetivo;
    }
    public String getLeyes() {
        return this.leyes;
    }
    
    public void setLeyes(String leyes) {
        this.leyes = leyes;
    }
    public Set getProcedimientos() {
        return this.procedimientos;
    }
    
    public void setProcedimientos(Set procedimientos) {
        this.procedimientos = procedimientos;
    }




}


