package com.entidad;
// Generated 27/01/2015 10:35:24 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Recurso generated by hbm2java
 */
public class Recurso  implements java.io.Serializable {


     private int idRecurso;
     private String nombre;
     private Set denuncias = new HashSet(0);

    public Recurso() {
    }

	
    public Recurso(int idRecurso, String nombre) {
        this.idRecurso = idRecurso;
        this.nombre = nombre;
    }
    public Recurso(int idRecurso, String nombre, Set denuncias) {
       this.idRecurso = idRecurso;
       this.nombre = nombre;
       this.denuncias = denuncias;
    }
   
    public int getIdRecurso() {
        return this.idRecurso;
    }
    
    public void setIdRecurso(int idRecurso) {
        this.idRecurso = idRecurso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDenuncias() {
        return this.denuncias;
    }
    
    public void setDenuncias(Set denuncias) {
        this.denuncias = denuncias;
    }




}


