package com.entidad;
// Generated 27/01/2015 10:35:24 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private UsuarioId id;
     private Plantel plantel;
     private Direccion direccion;
     private String nombre;
     private String apPaterno;
     private String apMaterno;
     private int edad;
     private String sexo;
     private String tipoSangre;
     private String contrasena;
     private boolean status;
     private String telefono;
     private String movil;
     private String email;

    
     private Set denuncias = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(UsuarioId id, Plantel plantel, Direccion direccion, String nombre, String apPaterno, String apMaterno, int edad, String sexo, String tipoSangre, String contrasena, boolean status, String telefono, String movil) {
        this.id = id;
        this.plantel = plantel;
        this.direccion = direccion;
        this.nombre = nombre;
        this.apPaterno = apPaterno;
        this.apMaterno = apMaterno;
        this.edad = edad;
        this.sexo = sexo;
        this.tipoSangre = tipoSangre;
        this.contrasena = contrasena;
        this.status = status;
        this.telefono = telefono;
        this.movil = movil;
    }
    public Usuario(UsuarioId id, Plantel plantel, Direccion direccion, String nombre, String apPaterno, String apMaterno, int edad, String sexo, String tipoSangre, String contrasena, boolean status, String telefono, String movil, Set denuncias) {
       this.id = id;
       this.plantel = plantel;
       this.direccion = direccion;
       this.nombre = nombre;
       this.apPaterno = apPaterno;
       this.apMaterno = apMaterno;
       this.edad = edad;
       this.sexo = sexo;
       this.tipoSangre = tipoSangre;
       this.contrasena = contrasena;
       this.status = status;
       this.telefono = telefono;
       this.movil = movil;
       this.denuncias = denuncias;
    }
   
    public UsuarioId getId() {
        return this.id;
    }
    
    public void setId(UsuarioId id) {
        this.id = id;
    }
    
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    public Plantel getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(Plantel plantel) {
        this.plantel = plantel;
    }
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApPaterno() {
        return this.apPaterno;
    }
    
    public void setApPaterno(String apPaterno) {
        this.apPaterno = apPaterno;
    }
    public String getApMaterno() {
        return this.apMaterno;
    }
    
    public void setApMaterno(String apMaterno) {
        this.apMaterno = apMaterno;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getTipoSangre() {
        return this.tipoSangre;
    }
    
    public void setTipoSangre(String tipoSangre) {
        this.tipoSangre = tipoSangre;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getMovil() {
        return this.movil;
    }
    
    public void setMovil(String movil) {
        this.movil = movil;
    }
    public Set getDenuncias() {
        return this.denuncias;
    }
    
    public void setDenuncias(Set denuncias) {
        this.denuncias = denuncias;
    }




}


