package com.entidad;
// Generated 27/01/2015 10:35:24 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;




/**
 * UsuarioId generated by hbm2java
 */

@Embeddable
public class UsuarioId  implements java.io.Serializable {

     @Column(name="idUsuario")
     private int idUsuario;
     @Column(name="direccionIdDireccion")
     private int direccionIdDireccion;
     @Column(name="plantelIdPlantel")
     private int plantelIdPlantel;
     @Column(name="plantelDireccionIdDireccion")
     private int plantelDireccionIdDireccion;

    public UsuarioId() {
    }

    public UsuarioId(int idUsuario, int direccionIdDireccion, int plantelIdPlantel, int plantelDireccionIdDireccion) {
       this.idUsuario = idUsuario;
       this.direccionIdDireccion = direccionIdDireccion;
       this.plantelIdPlantel = plantelIdPlantel;
       this.plantelDireccionIdDireccion = plantelDireccionIdDireccion;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getDireccionIdDireccion() {
        return this.direccionIdDireccion;
    }
    
    public void setDireccionIdDireccion(int direccionIdDireccion) {
        this.direccionIdDireccion = direccionIdDireccion;
    }
    public int getPlantelIdPlantel() {
        return this.plantelIdPlantel;
    }
    
    public void setPlantelIdPlantel(int plantelIdPlantel) {
        this.plantelIdPlantel = plantelIdPlantel;
    }
    public int getPlantelDireccionIdDireccion() {
        return this.plantelDireccionIdDireccion;
    }
    
    public void setPlantelDireccionIdDireccion(int plantelDireccionIdDireccion) {
        this.plantelDireccionIdDireccion = plantelDireccionIdDireccion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioId) ) return false;
		 UsuarioId castOther = ( UsuarioId ) other; 
         
		 return (this.getIdUsuario()==castOther.getIdUsuario())
 && (this.getDireccionIdDireccion()==castOther.getDireccionIdDireccion())
 && (this.getPlantelIdPlantel()==castOther.getPlantelIdPlantel())
 && (this.getPlantelDireccionIdDireccion()==castOther.getPlantelDireccionIdDireccion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUsuario();
         result = 37 * result + this.getDireccionIdDireccion();
         result = 37 * result + this.getPlantelIdPlantel();
         result = 37 * result + this.getPlantelDireccionIdDireccion();
         return result;
   }   


}


