package com.entidad;
// Generated 05-feb-2015 11:16:34 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActividadId generated by hbm2java
 */
@Embeddable
public class ActividadId  implements java.io.Serializable {


     private int idActividad;
     private int idProtocolo;

    public ActividadId() {
    }

    public ActividadId(int idActividad, int idProtocolo) {
       this.idActividad = idActividad;
       this.idProtocolo = idProtocolo;
    }
   


    @Column(name="idACTIVIDAD", nullable=false)
    public int getIdActividad() {
        return this.idActividad;
    }
    
    public void setIdActividad(int idActividad) {
        this.idActividad = idActividad;
    }


    @Column(name="idPROTOCOLO", nullable=false)
    public int getIdProtocolo() {
        return this.idProtocolo;
    }
    
    public void setIdProtocolo(int idProtocolo) {
        this.idProtocolo = idProtocolo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ActividadId) ) return false;
		 ActividadId castOther = ( ActividadId ) other; 
         
		 return (this.getIdActividad()==castOther.getIdActividad())
 && (this.getIdProtocolo()==castOther.getIdProtocolo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdActividad();
         result = 37 * result + this.getIdProtocolo();
         return result;
   }   


}


