package com.entidad;
// Generated 29/01/2015 10:51:11 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private int idActividad;
     private String descripcion;//aqui puse el comentario
     private Set procedimientos = new HashSet(0);

    public Actividad() {
    }

	
    public Actividad(int idActividad, String descripcion) {
        this.idActividad = idActividad;
        this.descripcion = descripcion;
    }
    public Actividad(int idActividad, String descripcion, Set procedimientos) {
       this.idActividad = idActividad;
       this.descripcion = descripcion;
       this.procedimientos = procedimientos;
    }
   
    public int getIdActividad() {
        return this.idActividad;
    }
    
    public void setIdActividad(int idActividad) {
        this.idActividad = idActividad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProcedimientos() {
        return this.procedimientos;
    }
    
    public void setProcedimientos(Set procedimientos) {
        this.procedimientos = procedimientos;
    }




}


