package com.entidad;
// Generated 05-feb-2015 11:16:34 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Actividad generated by hbm2java
 */
@Entity
@Table(name="actividad"
    ,catalog="sisap"
)
public class Actividad  implements java.io.Serializable {


     private ActividadId id;
     private Protocolo protocolo;
     private String descripcion;
     private String tipo;

    public Actividad() {
    }

	
    public Actividad(ActividadId id, Protocolo protocolo) {
        this.id = id;
        this.protocolo = protocolo;
    }
    public Actividad(ActividadId id, Protocolo protocolo, String descripcion, String tipo) {
       this.id = id;
       this.protocolo = protocolo;
       this.descripcion = descripcion;
       this.tipo = tipo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idActividad", column=@Column(name="idACTIVIDAD", nullable=false) ), 
        @AttributeOverride(name="idProtocolo", column=@Column(name="idPROTOCOLO", nullable=false) ) } )
    public ActividadId getId() {
        return this.id;
    }
    
    public void setId(ActividadId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPROTOCOLO", nullable=false, insertable=false, updatable=false)
    public Protocolo getProtocolo() {
        return this.protocolo;
    }
    
    public void setProtocolo(Protocolo protocolo) {
        this.protocolo = protocolo;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="tipo", length=45)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


