package com.entidad;
// Generated 30/01/2015 10:21:59 AM by Hibernate Tools 3.6.0



/**
 * Actividad generated by hbm2java
 */

public class Actividad  implements java.io.Serializable {


     private ActividadId id;
     private Protocolo protocolo;
     private String descripcion;
     private String tipo;

    public Actividad() {
    }

	
    public Actividad(ActividadId id, Protocolo protocolo, String descripcion) {
        this.id = id;
        this.protocolo = protocolo;
        this.descripcion = descripcion;
    }
    public Actividad(ActividadId id, Protocolo protocolo, String descripcion, String tipo) {
       this.id = id;
       this.protocolo = protocolo;
       this.descripcion = descripcion;
       this.tipo = tipo;
    }
   
    public ActividadId getId() {
        return this.id;
    }
    
    public void setId(ActividadId id) {
        this.id = id;
    }
    public Protocolo getProtocolo() {
        return this.protocolo;
    }
    
    public void setProtocolo(Protocolo protocolo) {
        this.protocolo = protocolo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


