package com.entidad;
// Generated 29/01/2015 10:51:11 PM by Hibernate Tools 3.6.0



/**
 * Archivo generated by hbm2java
 */
public class Archivo  implements java.io.Serializable {


     private int idArchivo;
     private String nombre;
     private String url;

    public Archivo() {
    }

	
    public Archivo(int idArchivo, String nombre) {
        this.idArchivo = idArchivo;
        this.nombre = nombre;
    }
    public Archivo(int idArchivo, String nombre, String url) {
       this.idArchivo = idArchivo;
       this.nombre = nombre;
       this.url = url;
    }
   
    public int getIdArchivo() {
        return this.idArchivo;
    }
    
    public void setIdArchivo(int idArchivo) {
        this.idArchivo = idArchivo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


