package com.entidad;
// Generated 30/01/2015 10:21:59 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private Integer idarea;
     private String nombre;
     private Set plantels = new HashSet(0);

    public Area() {
    }

	
    public Area(String nombre) {
        this.nombre = nombre;
    }
    public Area(String nombre, Set plantels) {
       this.nombre = nombre;
       this.plantels = plantels;
    }
   
    public Integer getIdarea() {
        return this.idarea;
    }
    
    public void setIdarea(Integer idarea) {
        this.idarea = idarea;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPlantels() {
        return this.plantels;
    }
    
    public void setPlantels(Set plantels) {
        this.plantels = plantels;
    }




}


