package com.entidad;
// Generated 27/01/2015 08:56:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int idCategoria;
     private String descripcion;
     private Set<Tipo> tipos = new HashSet<Tipo>(0);

    public Categoria() {
    }

	
    public Categoria(int idCategoria, String descripcion) {
        this.idCategoria = idCategoria;
        this.descripcion = descripcion;
    }
    public Categoria(int idCategoria, String descripcion, Set<Tipo> tipos) {
       this.idCategoria = idCategoria;
       this.descripcion = descripcion;
       this.tipos = tipos;
    }
   
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Tipo> getTipos() {
        return this.tipos;
    }
    
    public void setTipos(Set<Tipo> tipos) {
        this.tipos = tipos;
    }




}


