package com.entidad;
// Generated 29/01/2015 10:51:11 PM by Hibernate Tools 3.6.0



/**
 * Clave generated by hbm2java
 */
public class Clave  implements java.io.Serializable {


     private int idClave;
     private int numeroRecursos;
     private String clave;

    public Clave() {
    }

    public Clave(int idClave, int numeroRecursos, String clave) {
       this.idClave = idClave;
       this.numeroRecursos = numeroRecursos;
       this.clave = clave;
    }
   
    public int getIdClave() {
        return this.idClave;
    }
    
    public void setIdClave(int idClave) {
        this.idClave = idClave;
    }
    public int getNumeroRecursos() {
        return this.numeroRecursos;
    }
    
    public void setNumeroRecursos(int numeroRecursos) {
        this.numeroRecursos = numeroRecursos;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


