package com.entidad;
// Generated 27/01/2015 08:56:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Clave generated by hbm2java
 */
public class Clave  implements java.io.Serializable {


     private ClaveId id;
     private Prioridad prioridad;
     private Tipo tipo;
     private int numeroRecursos;
     private String clave;
     private Set<Denuncia> denuncias = new HashSet<Denuncia>(0);

    public Clave() {
    }

	
    public Clave(ClaveId id, Prioridad prioridad, Tipo tipo, int numeroRecursos, String clave) {
        this.id = id;
        this.prioridad = prioridad;
        this.tipo = tipo;
        this.numeroRecursos = numeroRecursos;
        this.clave = clave;
    }
    public Clave(ClaveId id, Prioridad prioridad, Tipo tipo, int numeroRecursos, String clave, Set<Denuncia> denuncias) {
       this.id = id;
       this.prioridad = prioridad;
       this.tipo = tipo;
       this.numeroRecursos = numeroRecursos;
       this.clave = clave;
       this.denuncias = denuncias;
    }
   
    public ClaveId getId() {
        return this.id;
    }
    
    public void setId(ClaveId id) {
        this.id = id;
    }
    public Prioridad getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(Prioridad prioridad) {
        this.prioridad = prioridad;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public int getNumeroRecursos() {
        return this.numeroRecursos;
    }
    
    public void setNumeroRecursos(int numeroRecursos) {
        this.numeroRecursos = numeroRecursos;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Set<Denuncia> getDenuncias() {
        return this.denuncias;
    }
    
    public void setDenuncias(Set<Denuncia> denuncias) {
        this.denuncias = denuncias;
    }




}


