package com.entidad;
// Generated 30/01/2015 10:21:59 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Clave generated by hbm2java
 */
public class Clave  implements java.io.Serializable {


     private int idClave;
     private Tipo tipo;
     private Prioridad prioridad;
     private Protocolo protocolo;
     private int numeroRecursos;
     private String descripcion;
     private String clave;
     private Set denuncias = new HashSet(0);

    public Clave() {
    }

	
    public Clave(int idClave, Tipo tipo, Prioridad prioridad, Protocolo protocolo, int numeroRecursos, String descripcion, String clave) {
        this.idClave = idClave;
        this.tipo = tipo;
        this.prioridad = prioridad;
        this.protocolo = protocolo;
        this.numeroRecursos = numeroRecursos;
        this.descripcion = descripcion;
        this.clave = clave;
    }
    public Clave(int idClave, Tipo tipo, Prioridad prioridad, Protocolo protocolo, int numeroRecursos, String descripcion, String clave, Set denuncias) {
       this.idClave = idClave;
       this.tipo = tipo;
       this.prioridad = prioridad;
       this.protocolo = protocolo;
       this.numeroRecursos = numeroRecursos;
       this.descripcion = descripcion;
       this.clave = clave;
       this.denuncias = denuncias;
    }
   
    public int getIdClave() {
        return this.idClave;
    }
    
    public void setIdClave(int idClave) {
        this.idClave = idClave;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public Prioridad getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(Prioridad prioridad) {
        this.prioridad = prioridad;
    }
    public Protocolo getProtocolo() {
        return this.protocolo;
    }
    
    public void setProtocolo(Protocolo protocolo) {
        this.protocolo = protocolo;
    }
    public int getNumeroRecursos() {
        return this.numeroRecursos;
    }
    
    public void setNumeroRecursos(int numeroRecursos) {
        this.numeroRecursos = numeroRecursos;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Set getDenuncias() {
        return this.denuncias;
    }
    
    public void setDenuncias(Set denuncias) {
        this.denuncias = denuncias;
    }




}


