package com.entidad;
// Generated 05-feb-2015 11:16:34 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClaveId generated by hbm2java
 */
@Embeddable
public class ClaveId  implements java.io.Serializable {


     private int idClave;
     private int idPrioridad;
     private int idTipo;
     private int idProtocolo;

    public ClaveId() {
    }

    public ClaveId(int idClave, int idPrioridad, int idTipo, int idProtocolo) {
       this.idClave = idClave;
       this.idPrioridad = idPrioridad;
       this.idTipo = idTipo;
       this.idProtocolo = idProtocolo;
    }
   


    @Column(name="idCLAVE", nullable=false)
    public int getIdClave() {
        return this.idClave;
    }
    
    public void setIdClave(int idClave) {
        this.idClave = idClave;
    }


    @Column(name="idPRIORIDAD", nullable=false)
    public int getIdPrioridad() {
        return this.idPrioridad;
    }
    
    public void setIdPrioridad(int idPrioridad) {
        this.idPrioridad = idPrioridad;
    }


    @Column(name="idTIPO", nullable=false)
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }


    @Column(name="idPROTOCOLO", nullable=false)
    public int getIdProtocolo() {
        return this.idProtocolo;
    }
    
    public void setIdProtocolo(int idProtocolo) {
        this.idProtocolo = idProtocolo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClaveId) ) return false;
		 ClaveId castOther = ( ClaveId ) other; 
         
		 return (this.getIdClave()==castOther.getIdClave())
 && (this.getIdPrioridad()==castOther.getIdPrioridad())
 && (this.getIdTipo()==castOther.getIdTipo())
 && (this.getIdProtocolo()==castOther.getIdProtocolo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdClave();
         result = 37 * result + this.getIdPrioridad();
         result = 37 * result + this.getIdTipo();
         result = 37 * result + this.getIdProtocolo();
         return result;
   }   


}


