package com.entidad;
// Generated 27/01/2015 08:56:50 PM by Hibernate Tools 3.6.0



/**
 * ClaveId generated by hbm2java
 */
public class ClaveId  implements java.io.Serializable {


     private int idClave;
     private int prioridadIdPrioridad;
     private int tipoIdTipo;

    public ClaveId() {
    }

    public ClaveId(int idClave, int prioridadIdPrioridad, int tipoIdTipo) {
       this.idClave = idClave;
       this.prioridadIdPrioridad = prioridadIdPrioridad;
       this.tipoIdTipo = tipoIdTipo;
    }
   
    public int getIdClave() {
        return this.idClave;
    }
    
    public void setIdClave(int idClave) {
        this.idClave = idClave;
    }
    public int getPrioridadIdPrioridad() {
        return this.prioridadIdPrioridad;
    }
    
    public void setPrioridadIdPrioridad(int prioridadIdPrioridad) {
        this.prioridadIdPrioridad = prioridadIdPrioridad;
    }
    public int getTipoIdTipo() {
        return this.tipoIdTipo;
    }
    
    public void setTipoIdTipo(int tipoIdTipo) {
        this.tipoIdTipo = tipoIdTipo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClaveId) ) return false;
		 ClaveId castOther = ( ClaveId ) other; 
         
		 return (this.getIdClave()==castOther.getIdClave())
 && (this.getPrioridadIdPrioridad()==castOther.getPrioridadIdPrioridad())
 && (this.getTipoIdTipo()==castOther.getTipoIdTipo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdClave();
         result = 37 * result + this.getPrioridadIdPrioridad();
         result = 37 * result + this.getTipoIdTipo();
         return result;
   }   


}


