package com.entidad;
// Generated 27/01/2015 08:56:50 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Denuncia generated by hbm2java
 */
public class Denuncia  implements java.io.Serializable {


     private DenunciaId id;
     private Archivo archivo;
     private Clave clave;
     private Recurso recurso;
     private Usuario usuario;
     private Date fechaRegistro;
     private String horaRegistro;
     private Date fechaFin;
     private String ubicacion;
     private String descripcion;

    public Denuncia() {
    }

    public Denuncia(DenunciaId id, Archivo archivo, Clave clave, Recurso recurso, Usuario usuario, Date fechaRegistro, String horaRegistro, Date fechaFin, String ubicacion, String descripcion) {
       this.id = id;
       this.archivo = archivo;
       this.clave = clave;
       this.recurso = recurso;
       this.usuario = usuario;
       this.fechaRegistro = fechaRegistro;
       this.horaRegistro = horaRegistro;
       this.fechaFin = fechaFin;
       this.ubicacion = ubicacion;
       this.descripcion = descripcion;
    }
   
    public DenunciaId getId() {
        return this.id;
    }
    
    public void setId(DenunciaId id) {
        this.id = id;
    }
    public Archivo getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(Archivo archivo) {
        this.archivo = archivo;
    }
    public Clave getClave() {
        return this.clave;
    }
    
    public void setClave(Clave clave) {
        this.clave = clave;
    }
    public Recurso getRecurso() {
        return this.recurso;
    }
    
    public void setRecurso(Recurso recurso) {
        this.recurso = recurso;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getHoraRegistro() {
        return this.horaRegistro;
    }
    
    public void setHoraRegistro(String horaRegistro) {
        this.horaRegistro = horaRegistro;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


