package com.entidad;
// Generated 30/01/2015 10:21:59 AM by Hibernate Tools 3.6.0



/**
 * DenunciaId generated by hbm2java
 */
public class DenunciaId  implements java.io.Serializable {


     private int idDenuncia;
     private int idClave;
     private int idArchivo;

    public DenunciaId() {
    }

    public DenunciaId(int idDenuncia, int idClave, int idArchivo) {
       this.idDenuncia = idDenuncia;
       this.idClave = idClave;
       this.idArchivo = idArchivo;
    }
   
    public int getIdDenuncia() {
        return this.idDenuncia;
    }
    
    public void setIdDenuncia(int idDenuncia) {
        this.idDenuncia = idDenuncia;
    }
    public int getIdClave() {
        return this.idClave;
    }
    
    public void setIdClave(int idClave) {
        this.idClave = idClave;
    }
    public int getIdArchivo() {
        return this.idArchivo;
    }
    
    public void setIdArchivo(int idArchivo) {
        this.idArchivo = idArchivo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DenunciaId) ) return false;
		 DenunciaId castOther = ( DenunciaId ) other; 
         
		 return (this.getIdDenuncia()==castOther.getIdDenuncia())
 && (this.getIdClave()==castOther.getIdClave())
 && (this.getIdArchivo()==castOther.getIdArchivo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDenuncia();
         result = 37 * result + this.getIdClave();
         result = 37 * result + this.getIdArchivo();
         return result;
   }   


}


