package com.entidad;
// Generated 29/01/2015 10:51:11 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Denuncia generated by hbm2java
 */
public class Denuncia  implements java.io.Serializable {


     private int idDenuncia;
     private Date fechaRegistro;
     private String horaRegistro;
     private Date fechaFin;
     private String ubicacion;
     private String descripcion;

    public Denuncia() {
    }

    public Denuncia(int idDenuncia, Date fechaRegistro, String horaRegistro, Date fechaFin, String ubicacion, String descripcion) {
       this.idDenuncia = idDenuncia;
       this.fechaRegistro = fechaRegistro;
       this.horaRegistro = horaRegistro;
       this.fechaFin = fechaFin;
       this.ubicacion = ubicacion;
       this.descripcion = descripcion;
    }
   
    public int getIdDenuncia() {
        return this.idDenuncia;
    }
    
    public void setIdDenuncia(int idDenuncia) {
        this.idDenuncia = idDenuncia;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getHoraRegistro() {
        return this.horaRegistro;
    }
    
    public void setHoraRegistro(String horaRegistro) {
        this.horaRegistro = horaRegistro;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


