package com.entidad;
// Generated 27/01/2015 08:56:50 PM by Hibernate Tools 3.6.0



/**
 * DenunciaId generated by hbm2java
 */
public class DenunciaId  implements java.io.Serializable {


     private int idDenuncia;
     private int usuarioIdUsuario;
     private int usuarioPlantelIdPlantel;
     private int claveIdClave;
     private int claveTipoIdTipo;
     private int clavePrioridadIdPrioridad;
     private int usuarioPlantelDireccionIdDireccion;
     private int usuarioDireccionIdDireccion;
     private int archivoIdArchivo;
     private int recursoIdRecurso;

    public DenunciaId() {
    }

    public DenunciaId(int idDenuncia, int usuarioIdUsuario, int usuarioPlantelIdPlantel, int claveIdClave, int claveTipoIdTipo, int clavePrioridadIdPrioridad, int usuarioPlantelDireccionIdDireccion, int usuarioDireccionIdDireccion, int archivoIdArchivo, int recursoIdRecurso) {
       this.idDenuncia = idDenuncia;
       this.usuarioIdUsuario = usuarioIdUsuario;
       this.usuarioPlantelIdPlantel = usuarioPlantelIdPlantel;
       this.claveIdClave = claveIdClave;
       this.claveTipoIdTipo = claveTipoIdTipo;
       this.clavePrioridadIdPrioridad = clavePrioridadIdPrioridad;
       this.usuarioPlantelDireccionIdDireccion = usuarioPlantelDireccionIdDireccion;
       this.usuarioDireccionIdDireccion = usuarioDireccionIdDireccion;
       this.archivoIdArchivo = archivoIdArchivo;
       this.recursoIdRecurso = recursoIdRecurso;
    }
   
    public int getIdDenuncia() {
        return this.idDenuncia;
    }
    
    public void setIdDenuncia(int idDenuncia) {
        this.idDenuncia = idDenuncia;
    }
    public int getUsuarioIdUsuario() {
        return this.usuarioIdUsuario;
    }
    
    public void setUsuarioIdUsuario(int usuarioIdUsuario) {
        this.usuarioIdUsuario = usuarioIdUsuario;
    }
    public int getUsuarioPlantelIdPlantel() {
        return this.usuarioPlantelIdPlantel;
    }
    
    public void setUsuarioPlantelIdPlantel(int usuarioPlantelIdPlantel) {
        this.usuarioPlantelIdPlantel = usuarioPlantelIdPlantel;
    }
    public int getClaveIdClave() {
        return this.claveIdClave;
    }
    
    public void setClaveIdClave(int claveIdClave) {
        this.claveIdClave = claveIdClave;
    }
    public int getClaveTipoIdTipo() {
        return this.claveTipoIdTipo;
    }
    
    public void setClaveTipoIdTipo(int claveTipoIdTipo) {
        this.claveTipoIdTipo = claveTipoIdTipo;
    }
    public int getClavePrioridadIdPrioridad() {
        return this.clavePrioridadIdPrioridad;
    }
    
    public void setClavePrioridadIdPrioridad(int clavePrioridadIdPrioridad) {
        this.clavePrioridadIdPrioridad = clavePrioridadIdPrioridad;
    }
    public int getUsuarioPlantelDireccionIdDireccion() {
        return this.usuarioPlantelDireccionIdDireccion;
    }
    
    public void setUsuarioPlantelDireccionIdDireccion(int usuarioPlantelDireccionIdDireccion) {
        this.usuarioPlantelDireccionIdDireccion = usuarioPlantelDireccionIdDireccion;
    }
    public int getUsuarioDireccionIdDireccion() {
        return this.usuarioDireccionIdDireccion;
    }
    
    public void setUsuarioDireccionIdDireccion(int usuarioDireccionIdDireccion) {
        this.usuarioDireccionIdDireccion = usuarioDireccionIdDireccion;
    }
    public int getArchivoIdArchivo() {
        return this.archivoIdArchivo;
    }
    
    public void setArchivoIdArchivo(int archivoIdArchivo) {
        this.archivoIdArchivo = archivoIdArchivo;
    }
    public int getRecursoIdRecurso() {
        return this.recursoIdRecurso;
    }
    
    public void setRecursoIdRecurso(int recursoIdRecurso) {
        this.recursoIdRecurso = recursoIdRecurso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DenunciaId) ) return false;
		 DenunciaId castOther = ( DenunciaId ) other; 
         
		 return (this.getIdDenuncia()==castOther.getIdDenuncia())
 && (this.getUsuarioIdUsuario()==castOther.getUsuarioIdUsuario())
 && (this.getUsuarioPlantelIdPlantel()==castOther.getUsuarioPlantelIdPlantel())
 && (this.getClaveIdClave()==castOther.getClaveIdClave())
 && (this.getClaveTipoIdTipo()==castOther.getClaveTipoIdTipo())
 && (this.getClavePrioridadIdPrioridad()==castOther.getClavePrioridadIdPrioridad())
 && (this.getUsuarioPlantelDireccionIdDireccion()==castOther.getUsuarioPlantelDireccionIdDireccion())
 && (this.getUsuarioDireccionIdDireccion()==castOther.getUsuarioDireccionIdDireccion())
 && (this.getArchivoIdArchivo()==castOther.getArchivoIdArchivo())
 && (this.getRecursoIdRecurso()==castOther.getRecursoIdRecurso());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDenuncia();
         result = 37 * result + this.getUsuarioIdUsuario();
         result = 37 * result + this.getUsuarioPlantelIdPlantel();
         result = 37 * result + this.getClaveIdClave();
         result = 37 * result + this.getClaveTipoIdTipo();
         result = 37 * result + this.getClavePrioridadIdPrioridad();
         result = 37 * result + this.getUsuarioPlantelDireccionIdDireccion();
         result = 37 * result + this.getUsuarioDireccionIdDireccion();
         result = 37 * result + this.getArchivoIdArchivo();
         result = 37 * result + this.getRecursoIdRecurso();
         return result;
   }   


}


