package com.entidad;
// Generated 29/01/2015 10:51:11 PM by Hibernate Tools 3.6.0



/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private int idEstado;
     private String descripcion;

    public Estado() {
    }

    public Estado(int idEstado, String descripcion) {
       this.idEstado = idEstado;
       this.descripcion = descripcion;
    }
   
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


