package com.entidad;
// Generated 05-feb-2015 11:16:34 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Notificacion generated by hbm2java
 */
@Entity
@Table(name="notificacion"
    ,catalog="sisap"
)
public class Notificacion  implements java.io.Serializable {


     private NotificacionId id;
     private Usuario usuario;
     private String asunto;
     private String descripcion;
     private String tipo;
     private Boolean status;
     private String medio;

    public Notificacion() {
    }

	
    public Notificacion(NotificacionId id, Usuario usuario) {
        this.id = id;
        this.usuario = usuario;
    }
    public Notificacion(NotificacionId id, Usuario usuario, String asunto, String descripcion, String tipo, Boolean status, String medio) {
       this.id = id;
       this.usuario = usuario;
       this.asunto = asunto;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.status = status;
       this.medio = medio;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idNotificacion", column=@Column(name="idNOTIFICACION", nullable=false) ), 
        @AttributeOverride(name="idUsuario", column=@Column(name="idUSUARIO", nullable=false, length=20) ), 
        @AttributeOverride(name="idPlantel", column=@Column(name="idPLANTEL", nullable=false) ), 
        @AttributeOverride(name="idArea", column=@Column(name="idArea", nullable=false) ) } )
    public NotificacionId getId() {
        return this.id;
    }
    
    public void setId(NotificacionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="idUSUARIO", referencedColumnName="idUSUARIO", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="idPLANTEL", referencedColumnName="idPLANTEL", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="idArea", referencedColumnName="id_area", nullable=false, insertable=false, updatable=false) } )
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="asunto", length=200)
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }

    
    @Column(name="descripcion", length=500)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="tipo", length=45)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

    
    @Column(name="medio", length=45)
    public String getMedio() {
        return this.medio;
    }
    
    public void setMedio(String medio) {
        this.medio = medio;
    }




}


