package com.entidad;
// Generated 30/01/2015 10:21:59 AM by Hibernate Tools 3.6.0



/**
 * NotificacionId generated by hbm2java
 */
public class NotificacionId  implements java.io.Serializable {


     private int idNotificacion;
     private String idUsuario;
     private int idPlantel;

    public NotificacionId() {
    }

    public NotificacionId(int idNotificacion, String idUsuario, int idPlantel) {
       this.idNotificacion = idNotificacion;
       this.idUsuario = idUsuario;
       this.idPlantel = idPlantel;
    }
   
    public int getIdNotificacion() {
        return this.idNotificacion;
    }
    
    public void setIdNotificacion(int idNotificacion) {
        this.idNotificacion = idNotificacion;
    }
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getIdPlantel() {
        return this.idPlantel;
    }
    
    public void setIdPlantel(int idPlantel) {
        this.idPlantel = idPlantel;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NotificacionId) ) return false;
		 NotificacionId castOther = ( NotificacionId ) other; 
         
		 return (this.getIdNotificacion()==castOther.getIdNotificacion())
 && ( (this.getIdUsuario()==castOther.getIdUsuario()) || ( this.getIdUsuario()!=null && castOther.getIdUsuario()!=null && this.getIdUsuario().equals(castOther.getIdUsuario()) ) )
 && (this.getIdPlantel()==castOther.getIdPlantel());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdNotificacion();
         result = 37 * result + ( getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode() );
         result = 37 * result + this.getIdPlantel();
         return result;
   }   


}


