package com.entidad;
// Generated 27/01/2015 08:56:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Notificacion generated by hbm2java
 */
public class Notificacion  implements java.io.Serializable {


     private int idNotificacion;
     private String asunto;
     private String descripcion;
     private Set<MedioDifusion> medioDifusions = new HashSet<MedioDifusion>(0);
     private Set<Procedimiento> procedimientos = new HashSet<Procedimiento>(0);

    public Notificacion() {
    }

	
    public Notificacion(int idNotificacion, String asunto, String descripcion) {
        this.idNotificacion = idNotificacion;
        this.asunto = asunto;
        this.descripcion = descripcion;
    }
    public Notificacion(int idNotificacion, String asunto, String descripcion, Set<MedioDifusion> medioDifusions, Set<Procedimiento> procedimientos) {
       this.idNotificacion = idNotificacion;
       this.asunto = asunto;
       this.descripcion = descripcion;
       this.medioDifusions = medioDifusions;
       this.procedimientos = procedimientos;
    }
   
    public int getIdNotificacion() {
        return this.idNotificacion;
    }
    
    public void setIdNotificacion(int idNotificacion) {
        this.idNotificacion = idNotificacion;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<MedioDifusion> getMedioDifusions() {
        return this.medioDifusions;
    }
    
    public void setMedioDifusions(Set<MedioDifusion> medioDifusions) {
        this.medioDifusions = medioDifusions;
    }
    public Set<Procedimiento> getProcedimientos() {
        return this.procedimientos;
    }
    
    public void setProcedimientos(Set<Procedimiento> procedimientos) {
        this.procedimientos = procedimientos;
    }




}


