package com.entidad;
// Generated 27/01/2015 08:56:50 PM by Hibernate Tools 3.6.0



/**
 * PlantelHasRecursoId generated by hbm2java
 */
public class PlantelHasRecursoId  implements java.io.Serializable {


     private int plantelIdPlantel;
     private int recursoIdRecurso;

    public PlantelHasRecursoId() {
    }

    public PlantelHasRecursoId(int plantelIdPlantel, int recursoIdRecurso) {
       this.plantelIdPlantel = plantelIdPlantel;
       this.recursoIdRecurso = recursoIdRecurso;
    }
   
    public int getPlantelIdPlantel() {
        return this.plantelIdPlantel;
    }
    
    public void setPlantelIdPlantel(int plantelIdPlantel) {
        this.plantelIdPlantel = plantelIdPlantel;
    }
    public int getRecursoIdRecurso() {
        return this.recursoIdRecurso;
    }
    
    public void setRecursoIdRecurso(int recursoIdRecurso) {
        this.recursoIdRecurso = recursoIdRecurso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlantelHasRecursoId) ) return false;
		 PlantelHasRecursoId castOther = ( PlantelHasRecursoId ) other; 
         
		 return (this.getPlantelIdPlantel()==castOther.getPlantelIdPlantel())
 && (this.getRecursoIdRecurso()==castOther.getRecursoIdRecurso());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPlantelIdPlantel();
         result = 37 * result + this.getRecursoIdRecurso();
         return result;
   }   


}


