package com.entidad;
// Generated 27/01/2015 08:56:50 PM by Hibernate Tools 3.6.0



/**
 * PlantelId generated by hbm2java
 */
public class PlantelId  implements java.io.Serializable {


     private int idPlantel;
     private int direccionIdDireccion;

    public PlantelId() {
    }

    public PlantelId(int idPlantel, int direccionIdDireccion) {
       this.idPlantel = idPlantel;
       this.direccionIdDireccion = direccionIdDireccion;
    }
   
    public int getIdPlantel() {
        return this.idPlantel;
    }
    
    public void setIdPlantel(int idPlantel) {
        this.idPlantel = idPlantel;
    }
    public int getDireccionIdDireccion() {
        return this.direccionIdDireccion;
    }
    
    public void setDireccionIdDireccion(int direccionIdDireccion) {
        this.direccionIdDireccion = direccionIdDireccion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlantelId) ) return false;
		 PlantelId castOther = ( PlantelId ) other; 
         
		 return (this.getIdPlantel()==castOther.getIdPlantel())
 && (this.getDireccionIdDireccion()==castOther.getDireccionIdDireccion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPlantel();
         result = 37 * result + this.getDireccionIdDireccion();
         return result;
   }   


}


