package com.entidad;
// Generated 29/01/2015 10:51:11 PM by Hibernate Tools 3.6.0



/**
 * Plantel generated by hbm2java
 */
public class Plantel  implements java.io.Serializable {


     private PlantelId id;
     private String nombre;
     private String telefono;
     private String extension;

    public Plantel() {
    }

	
    public Plantel(PlantelId id, String nombre, String telefono) {
        this.id = id;
        this.nombre = nombre;
        this.telefono = telefono;
    }
    public Plantel(PlantelId id, String nombre, String telefono, String extension) {
       this.id = id;
       this.nombre = nombre;
       this.telefono = telefono;
       this.extension = extension;
    }
   
    public PlantelId getId() {
        return this.id;
    }
    
    public void setId(PlantelId id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }




}


