package com.entidad;
// Generated 30/01/2015 10:21:59 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Plantel generated by hbm2java
 */
public class Plantel  implements java.io.Serializable {


     private int idPlantel;
     private Area area;
     private String nombre;
     private String telefono;
     private String extension;
     private String direccion;
     private byte[] coordenadaY;
     private byte[] coordenadaX;
     private Set usuarios = new HashSet(0);
     private Set recursos = new HashSet(0);

    public Plantel() {
    }

	
    public Plantel(int idPlantel, Area area, String nombre, String telefono, String direccion, byte[] coordenadaY, byte[] coordenadaX) {
        this.idPlantel = idPlantel;
        this.area = area;
        this.nombre = nombre;
        this.telefono = telefono;
        this.direccion = direccion;
        this.coordenadaY = coordenadaY;
        this.coordenadaX = coordenadaX;
    }
    public Plantel(int idPlantel, Area area, String nombre, String telefono, String extension, String direccion, byte[] coordenadaY, byte[] coordenadaX, Set usuarios, Set recursos) {
       this.idPlantel = idPlantel;
       this.area = area;
       this.nombre = nombre;
       this.telefono = telefono;
       this.extension = extension;
       this.direccion = direccion;
       this.coordenadaY = coordenadaY;
       this.coordenadaX = coordenadaX;
       this.usuarios = usuarios;
       this.recursos = recursos;
    }
   
    public int getIdPlantel() {
        return this.idPlantel;
    }
    
    public void setIdPlantel(int idPlantel) {
        this.idPlantel = idPlantel;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public byte[] getCoordenadaY() {
        return this.coordenadaY;
    }
    
    public void setCoordenadaY(byte[] coordenadaY) {
        this.coordenadaY = coordenadaY;
    }
    public byte[] getCoordenadaX() {
        return this.coordenadaX;
    }
    
    public void setCoordenadaX(byte[] coordenadaX) {
        this.coordenadaX = coordenadaX;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getRecursos() {
        return this.recursos;
    }
    
    public void setRecursos(Set recursos) {
        this.recursos = recursos;
    }




}


