package com.entidad;
// Generated 29/01/2015 10:51:11 PM by Hibernate Tools 3.6.0



/**
 * PlantelHasRecurso generated by hbm2java
 */
public class PlantelHasRecurso  implements java.io.Serializable {


     private PlantelHasRecursoId id;

    public PlantelHasRecurso() {
    }

    public PlantelHasRecurso(PlantelHasRecursoId id) {
       this.id = id;
    }
   
    public PlantelHasRecursoId getId() {
        return this.id;
    }
    
    public void setId(PlantelHasRecursoId id) {
        this.id = id;
    }




}


