package com.entidad;
// Generated 05-feb-2015 11:16:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Prioridad generated by hbm2java
 */
@Entity
@Table(name="prioridad"
    ,catalog="sisap"
)
public class Prioridad  implements java.io.Serializable {


     private Integer idPrioridad;
     private String descripcion;
     private Set<Clave> claves = new HashSet<Clave>(0);

    public Prioridad() {
    }

	
    public Prioridad(String descripcion) {
        this.descripcion = descripcion;
    }
    public Prioridad(String descripcion, Set<Clave> claves) {
       this.descripcion = descripcion;
       this.claves = claves;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPRIORIDAD", unique=true, nullable=false)
    public Integer getIdPrioridad() {
        return this.idPrioridad;
    }
    
    public void setIdPrioridad(Integer idPrioridad) {
        this.idPrioridad = idPrioridad;
    }

    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prioridad")
    public Set<Clave> getClaves() {
        return this.claves;
    }
    
    public void setClaves(Set<Clave> claves) {
        this.claves = claves;
    }




}


