package com.entidad;
// Generated 27/01/2015 08:56:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Prioridad generated by hbm2java
 */
public class Prioridad  implements java.io.Serializable {


     private int idPrioridad;
     private String descripcion;
     private Set<Clave> claves = new HashSet<Clave>(0);

    public Prioridad() {
    }

	
    public Prioridad(int idPrioridad, String descripcion) {
        this.idPrioridad = idPrioridad;
        this.descripcion = descripcion;
    }
    public Prioridad(int idPrioridad, String descripcion, Set<Clave> claves) {
       this.idPrioridad = idPrioridad;
       this.descripcion = descripcion;
       this.claves = claves;
    }
   
    public int getIdPrioridad() {
        return this.idPrioridad;
    }
    
    public void setIdPrioridad(int idPrioridad) {
        this.idPrioridad = idPrioridad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Clave> getClaves() {
        return this.claves;
    }
    
    public void setClaves(Set<Clave> claves) {
        this.claves = claves;
    }




}


