package com.entidad;
// Generated 29/01/2015 10:51:11 PM by Hibernate Tools 3.6.0



/**
 * Prioridad generated by hbm2java
 */
public class Prioridad  implements java.io.Serializable {


     private int idPrioridad;
     private String descripcion;

    public Prioridad() {
    }

    public Prioridad(int idPrioridad, String descripcion) {
       this.idPrioridad = idPrioridad;
       this.descripcion = descripcion;
    }
   
    public int getIdPrioridad() {
        return this.idPrioridad;
    }
    
    public void setIdPrioridad(int idPrioridad) {
        this.idPrioridad = idPrioridad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


