package com.entidad;
// Generated 27/01/2015 08:56:50 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Procedimiento generated by hbm2java
 */
public class Procedimiento  implements java.io.Serializable {


     private ProcedimientoId id;
     private Notificacion notificacion;
     private String descripcion;
     private Date fechaRegistro;
     private Set<Actividad> actividads = new HashSet<Actividad>(0);
     private Set<Protocolo> protocolos = new HashSet<Protocolo>(0);

    public Procedimiento() {
    }

	
    public Procedimiento(ProcedimientoId id, Notificacion notificacion, String descripcion, Date fechaRegistro) {
        this.id = id;
        this.notificacion = notificacion;
        this.descripcion = descripcion;
        this.fechaRegistro = fechaRegistro;
    }
    public Procedimiento(ProcedimientoId id, Notificacion notificacion, String descripcion, Date fechaRegistro, Set<Actividad> actividads, Set<Protocolo> protocolos) {
       this.id = id;
       this.notificacion = notificacion;
       this.descripcion = descripcion;
       this.fechaRegistro = fechaRegistro;
       this.actividads = actividads;
       this.protocolos = protocolos;
    }
   
    public ProcedimientoId getId() {
        return this.id;
    }
    
    public void setId(ProcedimientoId id) {
        this.id = id;
    }
    public Notificacion getNotificacion() {
        return this.notificacion;
    }
    
    public void setNotificacion(Notificacion notificacion) {
        this.notificacion = notificacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<Actividad> getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set<Actividad> actividads) {
        this.actividads = actividads;
    }
    public Set<Protocolo> getProtocolos() {
        return this.protocolos;
    }
    
    public void setProtocolos(Set<Protocolo> protocolos) {
        this.protocolos = protocolos;
    }




}


