package com.entidad;
// Generated 29/01/2015 10:51:11 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Procedimiento generated by hbm2java
 */
public class Procedimiento  implements java.io.Serializable {


     private int idProcedimiento;
     private String descripcion;
     private Date fechaRegistro;
     private Set protocolos = new HashSet(0);
     private Set actividads = new HashSet(0);

    public Procedimiento() {
    }

	
    public Procedimiento(int idProcedimiento, String descripcion, Date fechaRegistro) {
        this.idProcedimiento = idProcedimiento;
        this.descripcion = descripcion;
        this.fechaRegistro = fechaRegistro;
    }
    public Procedimiento(int idProcedimiento, String descripcion, Date fechaRegistro, Set protocolos, Set actividads) {
       this.idProcedimiento = idProcedimiento;
       this.descripcion = descripcion;
       this.fechaRegistro = fechaRegistro;
       this.protocolos = protocolos;
       this.actividads = actividads;
    }
   
    public int getIdProcedimiento() {
        return this.idProcedimiento;
    }
    
    public void setIdProcedimiento(int idProcedimiento) {
        this.idProcedimiento = idProcedimiento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getProtocolos() {
        return this.protocolos;
    }
    
    public void setProtocolos(Set protocolos) {
        this.protocolos = protocolos;
    }
    public Set getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set actividads) {
        this.actividads = actividads;
    }




}


