package com.entidad;
// Generated 27/01/2015 08:56:50 PM by Hibernate Tools 3.6.0



/**
 * ProcedimientoId generated by hbm2java
 */
public class ProcedimientoId  implements java.io.Serializable {


     private int idProcedimiento;
     private int notificacionIdNotificacion;

    public ProcedimientoId() {
    }

    public ProcedimientoId(int idProcedimiento, int notificacionIdNotificacion) {
       this.idProcedimiento = idProcedimiento;
       this.notificacionIdNotificacion = notificacionIdNotificacion;
    }
   
    public int getIdProcedimiento() {
        return this.idProcedimiento;
    }
    
    public void setIdProcedimiento(int idProcedimiento) {
        this.idProcedimiento = idProcedimiento;
    }
    public int getNotificacionIdNotificacion() {
        return this.notificacionIdNotificacion;
    }
    
    public void setNotificacionIdNotificacion(int notificacionIdNotificacion) {
        this.notificacionIdNotificacion = notificacionIdNotificacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProcedimientoId) ) return false;
		 ProcedimientoId castOther = ( ProcedimientoId ) other; 
         
		 return (this.getIdProcedimiento()==castOther.getIdProcedimiento())
 && (this.getNotificacionIdNotificacion()==castOther.getNotificacionIdNotificacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProcedimiento();
         result = 37 * result + this.getNotificacionIdNotificacion();
         return result;
   }   


}


