package com.entidad;
// Generated 30/01/2015 10:21:59 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Protocolo generated by hbm2java
 */
public class Protocolo  implements java.io.Serializable {


     private Integer idProtocolo;
     private String version;
     private String nombre;
     private String descripcion;
     private String objetivo;
     private String leyes;
     private String status;
     private Set actividads = new HashSet(0);
     private Set claves = new HashSet(0);

    public Protocolo() {
    }

	
    public Protocolo(String nombre, String descripcion, String objetivo) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.objetivo = objetivo;
    }
    public Protocolo(String nombre, String descripcion, String objetivo, String leyes, String status, Set actividads, Set claves) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.objetivo = objetivo;
       this.leyes = leyes;
       this.status = status;
       this.actividads = actividads;
       this.claves = claves;
    }
   
    public Integer getIdProtocolo() {
        return this.idProtocolo;
    }
    
    public void setIdProtocolo(Integer idProtocolo) {
        this.idProtocolo = idProtocolo;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getObjetivo() {
        return this.objetivo;
    }
    
    public void setObjetivo(String objetivo) {
        this.objetivo = objetivo;
    }
    public String getLeyes() {
        return this.leyes;
    }
    
    public void setLeyes(String leyes) {
        this.leyes = leyes;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set actividads) {
        this.actividads = actividads;
    }
    public Set getClaves() {
        return this.claves;
    }
    
    public void setClaves(Set claves) {
        this.claves = claves;
    }




}


