package com.entidad;
// Generated 29/01/2015 10:51:11 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Protocolo generated by hbm2java
 */
public class Protocolo  implements java.io.Serializable {


     private int idProtocolo;
     private String version;
     private String nombre;
     private String descripcion;
     private String objetivo;
     private String leyes;
     private Set procedimientos = new HashSet(0);

    public Protocolo() {
    }

	
    public Protocolo(int idProtocolo, String nombre, String descripcion) {
        this.idProtocolo = idProtocolo;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Protocolo(int idProtocolo, String nombre, String descripcion, String objetivo, String leyes, Set procedimientos) {
       this.idProtocolo = idProtocolo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.objetivo = objetivo;
       this.leyes = leyes;
       this.procedimientos = procedimientos;
    }
   
    public int getIdProtocolo() {
        return this.idProtocolo;
    }
    
    public void setIdProtocolo(int idProtocolo) {
        this.idProtocolo = idProtocolo;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getObjetivo() {
        return this.objetivo;
    }
    
    public void setObjetivo(String objetivo) {
        this.objetivo = objetivo;
    }
    public String getLeyes() {
        return this.leyes;
    }
    
    public void setLeyes(String leyes) {
        this.leyes = leyes;
    }
    public Set getProcedimientos() {
        return this.procedimientos;
    }
    
    public void setProcedimientos(Set procedimientos) {
        this.procedimientos = procedimientos;
    }




}


