package com.entidad;
// Generated 27/01/2015 08:56:50 PM by Hibernate Tools 3.6.0



/**
 * ProtocoloId generated by hbm2java
 */
public class ProtocoloId  implements java.io.Serializable {


     private int idProtocolo;
     private int estadoIdEstado;

    public ProtocoloId() {
    }

    public ProtocoloId(int idProtocolo, int estadoIdEstado) {
       this.idProtocolo = idProtocolo;
       this.estadoIdEstado = estadoIdEstado;
    }
   
    public int getIdProtocolo() {
        return this.idProtocolo;
    }
    
    public void setIdProtocolo(int idProtocolo) {
        this.idProtocolo = idProtocolo;
    }
    public int getEstadoIdEstado() {
        return this.estadoIdEstado;
    }
    
    public void setEstadoIdEstado(int estadoIdEstado) {
        this.estadoIdEstado = estadoIdEstado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProtocoloId) ) return false;
		 ProtocoloId castOther = ( ProtocoloId ) other; 
         
		 return (this.getIdProtocolo()==castOther.getIdProtocolo())
 && (this.getEstadoIdEstado()==castOther.getEstadoIdEstado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProtocolo();
         result = 37 * result + this.getEstadoIdEstado();
         return result;
   }   


}


