package com.entidad;
// Generated 30/01/2015 10:21:59 AM by Hibernate Tools 3.6.0



/**
 * Recurso generated by hbm2java
 */
public class Recurso  implements java.io.Serializable {


     private RecursoId id;
     private Plantel plantel;
     private String nombre;
     private String status;

    public Recurso() {
    }

	
    public Recurso(RecursoId id, Plantel plantel, String nombre) {
        this.id = id;
        this.plantel = plantel;
        this.nombre = nombre;
    }
    public Recurso(RecursoId id, Plantel plantel, String nombre, String status) {
       this.id = id;
       this.plantel = plantel;
       this.nombre = nombre;
       this.status = status;
    }
   
    public RecursoId getId() {
        return this.id;
    }
    
    public void setId(RecursoId id) {
        this.id = id;
    }
    public Plantel getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(Plantel plantel) {
        this.plantel = plantel;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


