package com.entidad;
// Generated 29/01/2015 10:51:11 PM by Hibernate Tools 3.6.0



/**
 * Recurso generated by hbm2java
 */
public class Recurso  implements java.io.Serializable {


     private int idRecurso;
     private String nombre;

    public Recurso() {
    }

    public Recurso(int idRecurso, String nombre) {
       this.idRecurso = idRecurso;
       this.nombre = nombre;
    }
   
    public int getIdRecurso() {
        return this.idRecurso;
    }
    
    public void setIdRecurso(int idRecurso) {
        this.idRecurso = idRecurso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


