package com.entidad;
// Generated 30/01/2015 10:21:59 AM by Hibernate Tools 3.6.0



/**
 * RecursoId generated by hbm2java
 */
public class RecursoId  implements java.io.Serializable {


     private String idRecurso;
     private int idPlantel;

    public RecursoId() {
    }

    public RecursoId(String idRecurso, int idPlantel) {
       this.idRecurso = idRecurso;
       this.idPlantel = idPlantel;
    }
   
    public String getIdRecurso() {
        return this.idRecurso;
    }
    
    public void setIdRecurso(String idRecurso) {
        this.idRecurso = idRecurso;
    }
    public int getIdPlantel() {
        return this.idPlantel;
    }
    
    public void setIdPlantel(int idPlantel) {
        this.idPlantel = idPlantel;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RecursoId) ) return false;
		 RecursoId castOther = ( RecursoId ) other; 
         
		 return ( (this.getIdRecurso()==castOther.getIdRecurso()) || ( this.getIdRecurso()!=null && castOther.getIdRecurso()!=null && this.getIdRecurso().equals(castOther.getIdRecurso()) ) )
 && (this.getIdPlantel()==castOther.getIdPlantel());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdRecurso() == null ? 0 : this.getIdRecurso().hashCode() );
         result = 37 * result + this.getIdPlantel();
         return result;
   }   


}


