package com.entidad;
// Generated 05-feb-2015 11:16:34 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RecursoId generated by hbm2java
 */
@Embeddable
public class RecursoId  implements java.io.Serializable {


     private String idRecurso;
     private int idPlantel;
     private int idArea;

    public RecursoId() {
    }

    public RecursoId(String idRecurso, int idPlantel, int idArea) {
       this.idRecurso = idRecurso;
       this.idPlantel = idPlantel;
       this.idArea = idArea;
    }
   


    @Column(name="idRECURSO", nullable=false, length=25)
    public String getIdRecurso() {
        return this.idRecurso;
    }
    
    public void setIdRecurso(String idRecurso) {
        this.idRecurso = idRecurso;
    }


    @Column(name="idPLANTEL", nullable=false)
    public int getIdPlantel() {
        return this.idPlantel;
    }
    
    public void setIdPlantel(int idPlantel) {
        this.idPlantel = idPlantel;
    }


    @Column(name="id_area", nullable=false)
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RecursoId) ) return false;
		 RecursoId castOther = ( RecursoId ) other; 
         
		 return ( (this.getIdRecurso()==castOther.getIdRecurso()) || ( this.getIdRecurso()!=null && castOther.getIdRecurso()!=null && this.getIdRecurso().equals(castOther.getIdRecurso()) ) )
 && (this.getIdPlantel()==castOther.getIdPlantel())
 && (this.getIdArea()==castOther.getIdArea());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdRecurso() == null ? 0 : this.getIdRecurso().hashCode() );
         result = 37 * result + this.getIdPlantel();
         result = 37 * result + this.getIdArea();
         return result;
   }   


}


