package com.entidad;
// Generated 05-feb-2015 11:16:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipo generated by hbm2java
 */
@Entity
@Table(name="tipo"
    ,catalog="sisap"
)
public class Tipo  implements java.io.Serializable {


     private Integer idTipo;
     private String descripcion;
     private Set<Clave> claves = new HashSet<Clave>(0);

    public Tipo() {
    }

	
    public Tipo(String descripcion) {
        this.descripcion = descripcion;
    }
    public Tipo(String descripcion, Set<Clave> claves) {
       this.descripcion = descripcion;
       this.claves = claves;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTIPO", unique=true, nullable=false)
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }

    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipo")
    public Set<Clave> getClaves() {
        return this.claves;
    }
    
    public void setClaves(Set<Clave> claves) {
        this.claves = claves;
    }




}


