package com.entidad;
// Generated 30/01/2015 10:21:59 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo  implements java.io.Serializable {


     private Integer idTipo;
     private String descripcion;
     private Set claves = new HashSet(0);

    public Tipo() {
    }

	
    public Tipo(String descripcion) {
        this.descripcion = descripcion;
    }
    public Tipo(String descripcion, Set claves) {
       this.descripcion = descripcion;
       this.claves = claves;
    }
   
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getClaves() {
        return this.claves;
    }
    
    public void setClaves(Set claves) {
        this.claves = claves;
    }




}


