package com.entidad;
// Generated 29/01/2015 10:51:11 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo  implements java.io.Serializable {


     private int idTipo;
     private String descripcion;
     private Set categorias = new HashSet(0);

    public Tipo() {
    }

	
    public Tipo(int idTipo, String descripcion) {
        this.idTipo = idTipo;
        this.descripcion = descripcion;
    }
    public Tipo(int idTipo, String descripcion, Set categorias) {
       this.idTipo = idTipo;
       this.descripcion = descripcion;
       this.categorias = categorias;
    }
   
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Set categorias) {
        this.categorias = categorias;
    }




}


