package com.entidad;
// Generated 30/01/2015 10:21:59 AM by Hibernate Tools 3.6.0



/**
 * UsuarioId generated by hbm2java
 */
public class UsuarioId  implements java.io.Serializable {


     private String idUsuario;
     private int idPlantel;

    public UsuarioId() {
    }

    public UsuarioId(String idUsuario, int idPlantel) {
       this.idUsuario = idUsuario;
       this.idPlantel = idPlantel;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getIdPlantel() {
        return this.idPlantel;
    }
    
    public void setIdPlantel(int idPlantel) {
        this.idPlantel = idPlantel;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioId) ) return false;
		 UsuarioId castOther = ( UsuarioId ) other; 
         
		 return ( (this.getIdUsuario()==castOther.getIdUsuario()) || ( this.getIdUsuario()!=null && castOther.getIdUsuario()!=null && this.getIdUsuario().equals(castOther.getIdUsuario()) ) )
 && (this.getIdPlantel()==castOther.getIdPlantel());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode() );
         result = 37 * result + this.getIdPlantel();
         return result;
   }   


}


