package com.entity;
// Generated 05-feb-2015 11:03:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Archivo generated by hbm2java
 */
@Entity
@Table(name="archivo"
    ,catalog="sisap"
)
public class Archivo  implements java.io.Serializable {


     private Integer idArchivo;
     private String nombre;
     private String url;
     private Set<Denuncia> denuncias = new HashSet<Denuncia>(0);

    public Archivo() {
    }

	
    public Archivo(String nombre) {
        this.nombre = nombre;
    }
    public Archivo(String nombre, String url, Set<Denuncia> denuncias) {
       this.nombre = nombre;
       this.url = url;
       this.denuncias = denuncias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idARCHIVO", unique=true, nullable=false)
    public Integer getIdArchivo() {
        return this.idArchivo;
    }
    
    public void setIdArchivo(Integer idArchivo) {
        this.idArchivo = idArchivo;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="url", length=45)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="archivo")
    public Set<Denuncia> getDenuncias() {
        return this.denuncias;
    }
    
    public void setDenuncias(Set<Denuncia> denuncias) {
        this.denuncias = denuncias;
    }




}


