package com.entity;
// Generated 05-feb-2015 11:03:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name="area"
    ,catalog="sisap"
)
public class Area  implements java.io.Serializable {


     private Integer idarea;
     private String nombre;
     private Set<Plantel> plantels = new HashSet<Plantel>(0);

    public Area() {
    }

	
    public Area(String nombre) {
        this.nombre = nombre;
    }
    public Area(String nombre, Set<Plantel> plantels) {
       this.nombre = nombre;
       this.plantels = plantels;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idarea", unique=true, nullable=false)
    public Integer getIdarea() {
        return this.idarea;
    }
    
    public void setIdarea(Integer idarea) {
        this.idarea = idarea;
    }

    
    @Column(name="nombre", nullable=false, length=60)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="area")
    public Set<Plantel> getPlantels() {
        return this.plantels;
    }
    
    public void setPlantels(Set<Plantel> plantels) {
        this.plantels = plantels;
    }




}


