package com.entity;
// Generated 05-feb-2015 11:03:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clave generated by hbm2java
 */
@Entity
@Table(name="clave"
    ,catalog="sisap"
)
public class Clave  implements java.io.Serializable {


     private ClaveId id;
     private Prioridad prioridad;
     private Protocolo protocolo;
     private Tipo tipo;
     private Integer numeroRecursos;
     private String descripcion;
     private String clave;
     private Set<Denuncia> denuncias = new HashSet<Denuncia>(0);

    public Clave() {
    }

	
    public Clave(ClaveId id, Prioridad prioridad, Protocolo protocolo, Tipo tipo) {
        this.id = id;
        this.prioridad = prioridad;
        this.protocolo = protocolo;
        this.tipo = tipo;
    }
    public Clave(ClaveId id, Prioridad prioridad, Protocolo protocolo, Tipo tipo, Integer numeroRecursos, String descripcion, String clave, Set<Denuncia> denuncias) {
       this.id = id;
       this.prioridad = prioridad;
       this.protocolo = protocolo;
       this.tipo = tipo;
       this.numeroRecursos = numeroRecursos;
       this.descripcion = descripcion;
       this.clave = clave;
       this.denuncias = denuncias;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idClave", column=@Column(name="idCLAVE", nullable=false) ), 
        @AttributeOverride(name="idPrioridad", column=@Column(name="idPRIORIDAD", nullable=false) ), 
        @AttributeOverride(name="idTipo", column=@Column(name="idTIPO", nullable=false) ), 
        @AttributeOverride(name="idProtocolo", column=@Column(name="idPROTOCOLO", nullable=false) ) } )
    public ClaveId getId() {
        return this.id;
    }
    
    public void setId(ClaveId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPRIORIDAD", nullable=false, insertable=false, updatable=false)
    public Prioridad getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(Prioridad prioridad) {
        this.prioridad = prioridad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPROTOCOLO", nullable=false, insertable=false, updatable=false)
    public Protocolo getProtocolo() {
        return this.protocolo;
    }
    
    public void setProtocolo(Protocolo protocolo) {
        this.protocolo = protocolo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTIPO", nullable=false, insertable=false, updatable=false)
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="numero_recursos")
    public Integer getNumeroRecursos() {
        return this.numeroRecursos;
    }
    
    public void setNumeroRecursos(Integer numeroRecursos) {
        this.numeroRecursos = numeroRecursos;
    }

    
    @Column(name="descripcion", length=60)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="clave", length=15)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clave")
    public Set<Denuncia> getDenuncias() {
        return this.denuncias;
    }
    
    public void setDenuncias(Set<Denuncia> denuncias) {
        this.denuncias = denuncias;
    }




}


