package com.entity;
// Generated 05-feb-2015 11:03:35 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Denuncia generated by hbm2java
 */
@Entity
@Table(name="denuncia"
    ,catalog="sisap"
)
public class Denuncia  implements java.io.Serializable {


     private DenunciaId id;
     private Archivo archivo;
     private Clave clave;
     private Usuario usuario;
     private Date fechaRegistro;
     private String horaRegistro;
     private Date fechaFin;
     private String ubicacion;
     private String estado;
     private String descripcion;
     private Boolean status;

    public Denuncia() {
    }

	
    public Denuncia(DenunciaId id, Archivo archivo, Clave clave, Usuario usuario) {
        this.id = id;
        this.archivo = archivo;
        this.clave = clave;
        this.usuario = usuario;
    }
    public Denuncia(DenunciaId id, Archivo archivo, Clave clave, Usuario usuario, Date fechaRegistro, String horaRegistro, Date fechaFin, String ubicacion, String estado, String descripcion, Boolean status) {
       this.id = id;
       this.archivo = archivo;
       this.clave = clave;
       this.usuario = usuario;
       this.fechaRegistro = fechaRegistro;
       this.horaRegistro = horaRegistro;
       this.fechaFin = fechaFin;
       this.ubicacion = ubicacion;
       this.estado = estado;
       this.descripcion = descripcion;
       this.status = status;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idDenuncia", column=@Column(name="idDENUNCIA", nullable=false) ), 
        @AttributeOverride(name="idClave", column=@Column(name="idCLAVE", nullable=false) ), 
        @AttributeOverride(name="idArchivo", column=@Column(name="idARCHIVO", nullable=false) ), 
        @AttributeOverride(name="idUsuario", column=@Column(name="idUSUARIO", nullable=false, length=20) ), 
        @AttributeOverride(name="idPlantel", column=@Column(name="idPLANTEL", nullable=false) ), 
        @AttributeOverride(name="idArea", column=@Column(name="idArea", nullable=false) ), 
        @AttributeOverride(name="idPrioridad", column=@Column(name="idPrioridad", nullable=false) ), 
        @AttributeOverride(name="idTipo", column=@Column(name="idTipo", nullable=false) ), 
        @AttributeOverride(name="idProtocolo", column=@Column(name="idProtocolo", nullable=false) ) } )
    public DenunciaId getId() {
        return this.id;
    }
    
    public void setId(DenunciaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idARCHIVO", nullable=false, insertable=false, updatable=false)
    public Archivo getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(Archivo archivo) {
        this.archivo = archivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="idCLAVE", referencedColumnName="idCLAVE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="idPrioridad", referencedColumnName="idPRIORIDAD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="idTipo", referencedColumnName="idTIPO", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="idProtocolo", referencedColumnName="idPROTOCOLO", nullable=false, insertable=false, updatable=false) } )
    public Clave getClave() {
        return this.clave;
    }
    
    public void setClave(Clave clave) {
        this.clave = clave;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="idUSUARIO", referencedColumnName="idUSUARIO", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="idPLANTEL", referencedColumnName="idPLANTEL", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="idArea", referencedColumnName="id_area", nullable=false, insertable=false, updatable=false) } )
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaRegistro", length=10)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    
    @Column(name="horaRegistro", length=45)
    public String getHoraRegistro() {
        return this.horaRegistro;
    }
    
    public void setHoraRegistro(String horaRegistro) {
        this.horaRegistro = horaRegistro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaFin", length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="ubicacion", length=100)
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

    
    @Column(name="estado", length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="descripcion", length=150)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


