package com.entity;
// Generated 05-feb-2015 11:03:35 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DenunciaId generated by hbm2java
 */
@Embeddable
public class DenunciaId  implements java.io.Serializable {


     private int idDenuncia;
     private int idClave;
     private int idArchivo;
     private String idUsuario;
     private int idPlantel;
     private int idArea;
     private int idPrioridad;
     private int idTipo;
     private int idProtocolo;

    public DenunciaId() {
    }

    public DenunciaId(int idDenuncia, int idClave, int idArchivo, String idUsuario, int idPlantel, int idArea, int idPrioridad, int idTipo, int idProtocolo) {
       this.idDenuncia = idDenuncia;
       this.idClave = idClave;
       this.idArchivo = idArchivo;
       this.idUsuario = idUsuario;
       this.idPlantel = idPlantel;
       this.idArea = idArea;
       this.idPrioridad = idPrioridad;
       this.idTipo = idTipo;
       this.idProtocolo = idProtocolo;
    }
   


    @Column(name="idDENUNCIA", nullable=false)
    public int getIdDenuncia() {
        return this.idDenuncia;
    }
    
    public void setIdDenuncia(int idDenuncia) {
        this.idDenuncia = idDenuncia;
    }


    @Column(name="idCLAVE", nullable=false)
    public int getIdClave() {
        return this.idClave;
    }
    
    public void setIdClave(int idClave) {
        this.idClave = idClave;
    }


    @Column(name="idARCHIVO", nullable=false)
    public int getIdArchivo() {
        return this.idArchivo;
    }
    
    public void setIdArchivo(int idArchivo) {
        this.idArchivo = idArchivo;
    }


    @Column(name="idUSUARIO", nullable=false, length=20)
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }


    @Column(name="idPLANTEL", nullable=false)
    public int getIdPlantel() {
        return this.idPlantel;
    }
    
    public void setIdPlantel(int idPlantel) {
        this.idPlantel = idPlantel;
    }


    @Column(name="idArea", nullable=false)
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }


    @Column(name="idPrioridad", nullable=false)
    public int getIdPrioridad() {
        return this.idPrioridad;
    }
    
    public void setIdPrioridad(int idPrioridad) {
        this.idPrioridad = idPrioridad;
    }


    @Column(name="idTipo", nullable=false)
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }


    @Column(name="idProtocolo", nullable=false)
    public int getIdProtocolo() {
        return this.idProtocolo;
    }
    
    public void setIdProtocolo(int idProtocolo) {
        this.idProtocolo = idProtocolo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DenunciaId) ) return false;
		 DenunciaId castOther = ( DenunciaId ) other; 
         
		 return (this.getIdDenuncia()==castOther.getIdDenuncia())
 && (this.getIdClave()==castOther.getIdClave())
 && (this.getIdArchivo()==castOther.getIdArchivo())
 && ( (this.getIdUsuario()==castOther.getIdUsuario()) || ( this.getIdUsuario()!=null && castOther.getIdUsuario()!=null && this.getIdUsuario().equals(castOther.getIdUsuario()) ) )
 && (this.getIdPlantel()==castOther.getIdPlantel())
 && (this.getIdArea()==castOther.getIdArea())
 && (this.getIdPrioridad()==castOther.getIdPrioridad())
 && (this.getIdTipo()==castOther.getIdTipo())
 && (this.getIdProtocolo()==castOther.getIdProtocolo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDenuncia();
         result = 37 * result + this.getIdClave();
         result = 37 * result + this.getIdArchivo();
         result = 37 * result + ( getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode() );
         result = 37 * result + this.getIdPlantel();
         result = 37 * result + this.getIdArea();
         result = 37 * result + this.getIdPrioridad();
         result = 37 * result + this.getIdTipo();
         result = 37 * result + this.getIdProtocolo();
         return result;
   }   


}


