package com.entity;
// Generated 05-feb-2015 11:03:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Plantel generated by hbm2java
 */
@Entity
@Table(name="plantel"
    ,catalog="sisap"
)
public class Plantel  implements java.io.Serializable {


     private PlantelId id;
     private Area area;
     private String nombre;
     private String telefono;
     private String extension;
     private String direccion;
     private byte[] coordenadaY;
     private byte[] coordenadaX;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Recurso> recursos = new HashSet<Recurso>(0);

    public Plantel() {
    }

	
    public Plantel(PlantelId id, Area area) {
        this.id = id;
        this.area = area;
    }
    public Plantel(PlantelId id, Area area, String nombre, String telefono, String extension, String direccion, byte[] coordenadaY, byte[] coordenadaX, Set<Usuario> usuarios, Set<Recurso> recursos) {
       this.id = id;
       this.area = area;
       this.nombre = nombre;
       this.telefono = telefono;
       this.extension = extension;
       this.direccion = direccion;
       this.coordenadaY = coordenadaY;
       this.coordenadaX = coordenadaX;
       this.usuarios = usuarios;
       this.recursos = recursos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idPlantel", column=@Column(name="idPLANTEL", nullable=false) ), 
        @AttributeOverride(name="areaIdarea", column=@Column(name="area_idarea", nullable=false) ) } )
    public PlantelId getId() {
        return this.id;
    }
    
    public void setId(PlantelId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="area_idarea", nullable=false, insertable=false, updatable=false)
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }

    
    @Column(name="nombre", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="telefono", length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="extension", length=45)
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }

    
    @Column(name="direccion", length=16777215)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="coordenadaY")
    public byte[] getCoordenadaY() {
        return this.coordenadaY;
    }
    
    public void setCoordenadaY(byte[] coordenadaY) {
        this.coordenadaY = coordenadaY;
    }

    
    @Column(name="coordenadaX")
    public byte[] getCoordenadaX() {
        return this.coordenadaX;
    }
    
    public void setCoordenadaX(byte[] coordenadaX) {
        this.coordenadaX = coordenadaX;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="plantel")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="plantel")
    public Set<Recurso> getRecursos() {
        return this.recursos;
    }
    
    public void setRecursos(Set<Recurso> recursos) {
        this.recursos = recursos;
    }




}


