package com.entity;
// Generated 05-feb-2015 11:03:35 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlantelId generated by hbm2java
 */
@Embeddable
public class PlantelId  implements java.io.Serializable {


     private int idPlantel;
     private int areaIdarea;

    public PlantelId() {
    }

    public PlantelId(int idPlantel, int areaIdarea) {
       this.idPlantel = idPlantel;
       this.areaIdarea = areaIdarea;
    }
   


    @Column(name="idPLANTEL", nullable=false)
    public int getIdPlantel() {
        return this.idPlantel;
    }
    
    public void setIdPlantel(int idPlantel) {
        this.idPlantel = idPlantel;
    }


    @Column(name="area_idarea", nullable=false)
    public int getAreaIdarea() {
        return this.areaIdarea;
    }
    
    public void setAreaIdarea(int areaIdarea) {
        this.areaIdarea = areaIdarea;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlantelId) ) return false;
		 PlantelId castOther = ( PlantelId ) other; 
         
		 return (this.getIdPlantel()==castOther.getIdPlantel())
 && (this.getAreaIdarea()==castOther.getAreaIdarea());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPlantel();
         result = 37 * result + this.getAreaIdarea();
         return result;
   }   


}


