package com.entity;
// Generated 05-feb-2015 11:03:35 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Recurso generated by hbm2java
 */
@Entity
@Table(name="recurso"
    ,catalog="sisap"
)
public class Recurso  implements java.io.Serializable {


     private RecursoId id;
     private Plantel plantel;
     private String nombre;
     private String status;

    public Recurso() {
    }

	
    public Recurso(RecursoId id, Plantel plantel) {
        this.id = id;
        this.plantel = plantel;
    }
    public Recurso(RecursoId id, Plantel plantel, String nombre, String status) {
       this.id = id;
       this.plantel = plantel;
       this.nombre = nombre;
       this.status = status;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idRecurso", column=@Column(name="idRECURSO", nullable=false, length=25) ), 
        @AttributeOverride(name="idPlantel", column=@Column(name="idPLANTEL", nullable=false) ), 
        @AttributeOverride(name="idArea", column=@Column(name="id_area", nullable=false) ) } )
    public RecursoId getId() {
        return this.id;
    }
    
    public void setId(RecursoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="idPLANTEL", referencedColumnName="idPLANTEL", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="id_area", referencedColumnName="area_idarea", nullable=false, insertable=false, updatable=false) } )
    public Plantel getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(Plantel plantel) {
        this.plantel = plantel;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


